#!/usr/bin/env python
# coding: utf-8

# In[2]:


print ("Hellow World")


# # Artha Aprilla Mulya Agung
# ## 20/462132/PA/20104

# In[6]:


#==========================#
#    Tugas Praktikum 05    #
#      Program halo.py     #
# by. Artha Aprilla M A    #
#                          #
#==========================#


# In[ ]:





# In[ ]:




